services:
  postgres:
    image: postgres:16-alpine
    container_name: supercomputers-db
    environment:
      POSTGRES_DB: supercomputers
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: superpass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U superuser -d supercomputers"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: